import type { Strategy } from './types';

export const initialStrategies: Strategy[] = [
  {
    id: 'strat-1',
    name: 'EMA Cross – BTC/USDT',
    type: 'Momentum',
    market: 'BTC/USDT',
    timeframe: '1h',
    broker: 'Delta Exchange (Paper)',
    trades30d: 45,
    winRate: 68,
    netPnl: 12345.67,
    maxDrawdown: 12.5,
    status: 'Running',
    description: 'A classic trend-following strategy that enters when a short-term EMA crosses above a long-term EMA.',
    riskPerTrade: 1,
    maxOpenPositions: 1,
    notes: 'Performs well in strong trends but gets chopped up in ranging markets. Need to add a volatility filter.',
  },
  {
    id: 'strat-2',
    name: 'RSI Reversal – ETH/USDT',
    type: 'Mean Reversion',
    market: 'ETH/USDT',
    timeframe: '4h',
    broker: 'Binance Futures',
    trades30d: 12,
    winRate: 75,
    netPnl: 8765.43,
    maxDrawdown: 8.2,
    status: 'Running',
    description: 'Enters short on overbought RSI ( >70) and long on oversold RSI ( <30), targeting a reversion to the mean.',
    riskPerTrade: 2,
    maxOpenPositions: 2,
    notes: 'Very profitable but requires patience. Sometimes misses out on strong trend continuations.',
  },
  {
    id: 'strat-3',
    name: 'Breakout Pullback – BTC Perp',
    type: 'Breakout',
    market: 'BTC/USDT',
    timeframe: '15m',
    broker: 'Bybit',
    trades30d: 88,
    winRate: 55,
    netPnl: -2345.00,
    maxDrawdown: 25.1,
    status: 'Paused',
    description: 'Identifies a key level breakout, waits for a pullback to that level, and enters in the direction of the breakout.',
    riskPerTrade: 0.5,
    maxOpenPositions: 3,
    notes: 'Currently underperforming due to too many false breakouts. Paused for review.',
  },
   {
    id: 'strat-4',
    name: 'Scalping POC',
    type: 'Scalping',
    market: 'SOL/USDT',
    timeframe: '5m',
    broker: 'Paper',
    trades30d: 0,
    winRate: 0,
    netPnl: 0,
    maxDrawdown: 0,
    status: 'Draft',
    description: 'A new idea for a high-frequency scalping strategy based on volume profile point of control.',
    riskPerTrade: 0.25,
    maxOpenPositions: 5,
    notes: 'Still in the planning phase. Needs backtesting.',
  },
];

export const mockTradeLog = [
    { id: 'log-1', time: '2024-07-29 09:15:03', signal: 'BUY', asset: 'BTC/USDT', price: 68500.50, result: '+$1,250' },
    { id: 'log-2', time: '2024-07-28 14:30:10', signal: 'SELL', asset: 'BTC/USDT', price: 69100.00, result: '-$750' },
    { id: 'log-3', time: '2024-07-28 02:05:45', signal: 'BUY', asset: 'BTC/USDT', price: 68200.00, result: '+$900' },
    { id: 'log-4', time: '2024-07-27 18:00:00', signal: 'SELL', asset: 'BTC/USDT', price: 68950.00, result: '+$1,100' },
];